FROM python:3.7-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
COPY . .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
