# Generated by Django 2.2.2 on 2019-08-03 16:14

import books.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=75, null=True, verbose_name='Book title')),
                ('published_date', models.CharField(blank=True, max_length=10, null=True, validators=[books.validators.check_if_value_is_date, books.validators.max_year_validator], verbose_name='Publishing date')),
                ('pages', models.IntegerField(blank=True, null=True, validators=[books.validators.check_if_value_is_negative], verbose_name='Number of pages')),
                ('language', models.CharField(blank=True, max_length=2, null=True, verbose_name='Language')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='IndustryIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, verbose_name='Type')),
                ('identifier', models.CharField(max_length=25, verbose_name='Identifier')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_identifiers', to='books.Book', verbose_name='Book')),
            ],
        ),
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_thumbnail', models.URLField(blank=True, default=None, verbose_name='Small thumbnail')),
                ('thumbnail', models.URLField(blank=True, default=None, verbose_name='Thumbnail')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.Book', verbose_name='Book')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150, verbose_name='Author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='books.Book', verbose_name='Book')),
            ],
        ),
    ]
