# Generated by Django 2.2.2 on 2019-06-27 02:33

import books.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Book title')),
                ('authors', models.CharField(max_length=150, verbose_name='Authors')),
                ('published_date', models.IntegerField(validators=[books.validators.check_if_value_is_negative, books.validators.max_year_validator], verbose_name='Publishing date')),
                ('pages', models.IntegerField(validators=[books.validators.check_if_value_is_negative], verbose_name='Number of pages')),
                ('language', models.CharField(max_length=2, verbose_name='Language')),
                ('image', models.URLField(blank=True, default=None, null=True, verbose_name='Image')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='IndustryIdentifiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, verbose_name='Type')),
                ('identifier', models.CharField(max_length=25, verbose_name='Identifier')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_identifiers', to='books.Book', verbose_name='Book')),
            ],
        ),
    ]
