# Generated by Django 2.2.2 on 2019-08-07 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_thumbnail', models.URLField(blank=True, default=None, verbose_name='Small thumbnail')),
                ('thumbnail', models.URLField(blank=True, default=None, verbose_name='Thumbnail')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='books.Book', verbose_name='Book')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageLink',
        ),
    ]
