# Generated by Django 2.2.2 on 2019-06-27 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190627_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150, verbose_name='Author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='books.Book', verbose_name='Book')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, verbose_name='Type')),
                ('identifier', models.CharField(max_length=25, verbose_name='Identifier')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_identifier', to='books.Book', verbose_name='Book')),
            ],
        ),
        migrations.RenameModel(
            old_name='ImageLinks',
            new_name='ImageLink',
        ),
        migrations.RemoveField(
            model_name='industryidentifiers',
            name='book',
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
        migrations.DeleteModel(
            name='IndustryIdentifiers',
        ),
    ]
